name: "styles-check"

on: workflow_call

jobs:
  styles-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Bun
        uses: oven-sh/setup-bun@43b2dc9ae87f6949ab33cd393f0ded6654d2cc9b # v1
        with:
          bun-version: "1.0.1"

      - name: Check
        run: make styles-check

